### ISSUE TITLE
Add blsct wallet type for createwallet rpc method

### ISSUE THREAD

**Issue by sakdeniz** [navcoin/navcoin#136]
### Please describe the feature you'd like to see added.

Currently `createwallet` rpc method not supports wallet type for "blsct". It should be added for creating blsct wallets.

**Comment by aguycalled** [comment]
addressed in https://github.com/navcoin/navcoin/commit/54a9c893aaaa9715440bbf29989095a5edb25427

**Comment by sakdeniz** [comment]
fixed
