### ISSUE TITLE
getnewaddress rpc method not works

### ISSUE THREAD

**Issue by sakdeniz** [navcoin/navcoin#149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

If the wallet is created with the "createwallet" rpc method and the "getnewaddress" rpc method is called to derive a new blsct address, it throws the following error.

"SubAddress: no valid blsct keys"

### Expected behaviour

It should generate a new blsct address.

### Steps to reproduce

getnewaddress "" blsct

### Relevant log output

SubAddress: no valid blsct keys

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

blsct-pos

### Operating system and version

Ubuntu 22.04

**Comment by aguycalled** [comment]
can you write the exact steps to reproduce the issue, including how do you create the wallet?

**Comment by aguycalled** [comment]
this issue only happens when the passphrase is null

**Comment by aguycalled** [comment]
should be now fixed in 8f540069c6

**Comment by sakdeniz** [comment]
its fixed in 8f540069c6
