### ISSUE TITLE
stakelock rpc command generates unnecessary blsct address.

### ISSUE THREAD

**Issue by sakdeniz** [navcoin/navcoin#151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

stakelock rpc command generates unnecessary blsct address.

### Expected behaviour

It should not generate a new address.

### Steps to reproduce

stakelock 100

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

blsct-pos

### Operating system and version

Ubuntu 22.04

**Comment by aguycalled** [comment]
addressed in cde23c1b52

**Comment by sakdeniz** [comment]
issue fixed
