### ISSUE TITLE
wallet: modify signing magic string

### ISSUE THREAD

**Issue by aguycalled** [navcoin/navcoin#20]
The magic string used for prefixing messages to be signed needs to be changed to:

```
"Navcoin Signed Message:\n"
```

**Comment by mxaddict** [comment]
> 

Where do I find this magic string?

**Comment by aguycalled** [comment]
`src/util/message.cpp`

**Comment by mxaddict** [comment]
Ahh, it's already modified in my branding PR

**Comment by mxaddict** [comment]
> Ahh, it's already modified in my branding PR #29

This is going to be re-done with a less invasive PR that changes minimal code to avoid large conflicts with upstream as per discussed with @aguycalled

**Comment by mxaddict** [comment]
This is now covered by #38
