### ISSUE TITLE
refactor: rename data folder and configuration file

### ISSUE THREAD

**Issue by aguycalled** [navcoin/navcoin#21]
The default configuration file and data folder must be renamed to `navcoin.conf` and `navcoin8` / `Navcoin8` respectively.

References in the [documentation](https://github.com/navcoin/navcoin/blob/master/doc/bitcoin-conf.md) must be updated.

**Comment by mxaddict** [comment]
This is covered by PR #29

**Comment by mxaddict** [comment]
> This is covered by PR #29

This is going to be re-done with a less invasive PR that changes minimal code to avoid large conflicts with upstream as per discussed with @aguycalled

**Comment by mxaddict** [comment]
This is now covered by #37
