### ISSUE TITLE
wallet: modify address prefix

### ISSUE THREAD

**Issue by aguycalled** [navcoin/navcoin#43]
Address prefixes are defined in https://github.com/navcoin/navcoin/blob/master/src/chainparams.cpp.

We need to substitute the Bitcoin prefixes with prefixes for public addresses unique to the new chain.

Mainnet: `nav`
Testnet: `tnav`
Signet: `snav`
Regnet: `rnav`

**Comment by mxaddict** [comment]
@aguycalled this has been implemented already right?

**Comment by aguycalled** [comment]
not yet, we should ask in the community how would they want the addresses to look like

**Comment by aguycalled** [comment]
what I suggested in the top post is my idea

**Comment by mxaddict** [comment]
I think these are reasonable:
```
Mainnet: nav
Testnet: tnav
Signet: snav
Regnet: rnav
```

**Comment by mxaddict** [comment]
Hmm, just realized, won't we only have private addresses once we launch?
