### ISSUE TITLE
wallet: disable the wallet UI

### ISSUE THREAD

**Issue by sinetek** [navcoin/navcoin#58]
Since after consideration we're not going to be using the GUI it can be perhaps disabled.
I put up this issue to see what you think.

**Comment by aguycalled** [comment]
Should we also remove the code related to QT, or just disable its compilation?

I tend to think we should also remove it.

**Comment by mxaddict** [comment]
> Should we also remove the code related to QT, or just disable its compilation?
> 
> I tend to think we should also remove it.

I think since we are not going to be using it in the future, might make sense to just remove it

**Comment by aguycalled** [comment]
Another option we considered, was to restrict the UI to just the Node window, to enable interaction through the console.

**Comment by sinetek** [comment]
https://github.com/sinetek/navcoin/commit/e9f22328830b95d9325238f817f8cbdecfd3f27a

what do you think of axing all this stuff?  here's a commit you can cherry-pick.  By the way I can't do pull requests because I can't make a fork of this repo because I already have a fork by the name 'bitcoin' and github doesn't like making more than one fork per project. I'm not sure how to resolve *that*.

**Comment by aguycalled** [comment]
Could you now create a pull request with the changes?
