### ISSUE TITLE
p2p: update protocol magic bytes

### ISSUE THREAD

**Issue by aguycalled** [navcoin/navcoin#9]
Each network (mainnet, testnet, regnet) needs to get their protocol magic bytes updated to unique Navcoin values. 

Ideally they should not be equal to other bitcoin-based networks, but for the sake of simplicity, they can be set randomly.

**Comment by isgulkov** [comment]
So, this is [`pchMessageStart` in `src/chainparams.cpp`](https://github.com/navcoin/navcoin/blob/master/src/chainparams.cpp#L221-L224).

As this is a change in the network protocol, we'll also need to support the old values ([here](https://github.com/navcoin/navcoin/blob/master/src/net.cpp#L735-L738) and perhaps somewhere else) until old versions are phased out

> Ideally they should not be equal to other bitcoin-based networks, but for the sake of simplicity, they can be set randomly

Random values are good enough — 4 bytes is too much entropy for any collision to occur, realistically speaking. One caveat is that the randomness should be good *(ran this on an `i7-3615QM` with `RDRAND` support)*:

```bash
$ hexdump -n 12 -e '4/1 "%02x " "\n"' /dev/random
11 56 a6 9d
05 c9 85 bd
89 a7 7f 85
```

**Comment by aguycalled** [comment]
Thanks Ilya for your observation and your careful approach. In our specific case we don't need to keep backwards compatibility with old nodes as we are starting a new chain. And essentially, we want to make old clients incompatible with the new one so their interactions are prevented.

**Comment by mxaddict** [comment]
Since the code changes for this were already merged, I think we should be closing this issue?
